spring:
  application:
    name: restapi-product

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/restapi-product;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ''

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    show-sql: true

  sql:
    init:
      mode: always

logging:
  level:
    root: INFO

springdoc:
  title: "Product Api"
  description: "API to obtain final calculated prices of a product"
  version: "v1.0.0"
  contact-name: "Manuel Angel Picallo Pérez"
  contact-email: "mapicalloperez@hotmail.com"

  api-docs:
    path: /api-docs

  swagger-ui:
    path: /swagger-ui.html
